package Capa_Presentacion;

import Capa_Logica.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Flores Coronel Gabriel Angel
 */
public class frmLogin extends javax.swing.JDialog {

    Byte numIntentos = 0;
    public String dniUsuario = "";

    private frmMenuPrincipal menuPrincipal;

    /**
     * Creates new form frmLogin
     */
    public frmLogin(java.awt.Frame parent, boolean modal, frmMenuPrincipal menuPrincipal) {
        super(parent, modal);
        initComponents();
        this.menuPrincipal = menuPrincipal; // Guarda la referencia
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNroDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio de Sesión");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logoempresa.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nro. DNI:");

        txtNroDNI.setText("12345678");
        txtNroDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroDNIActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Clave:");

        btnIngresar.setBackground(new java.awt.Color(255, 51, 51));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtClave.setText("admin123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNroDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        // Validamos campos para evitar cualquier error 
        String dni = txtNroDNI.getText();
        String clave = new String(txtClave.getPassword());

        //Para evitar que estén vacíos los campos DNI Y clave
        if (dni.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El DNI y la clave no pueden estar vacíos.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //DNI debe tener exactamente 8 dígitos
        if (!dni.matches("\\d{8}")) { // Valida 8 dígitos numéricos
            JOptionPane.showMessageDialog(null, "El DNI debe tener 8 dígitos numéricos.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Ahora si todo está correcto, pasamos a logearnos sin problema
        try {
            String[] info_usu = Usuario.login(dni, clave);
            if(info_usu[0] == null) {
                numIntentos++;
                if(numIntentos >= 3) {
                    JOptionPane.showMessageDialog(null, "Acceso Incorrecto. Verifique sus credenciales y estado.", "Error de Autenticación", JOptionPane.WARNING_MESSAGE);
                    System.exit(0);
                }
            } else {
                if(info_usu[3].equalsIgnoreCase("disponible")) {
                    JOptionPane.showMessageDialog(null, "Bienvenido al sistema " + info_usu[0] + ", " + info_usu[1]);
                    menuPrincipal.setInfoUsuarioText(info_usu[0], info_usu[1], info_usu[2], info_usu[3]);
                    menuPrincipal.mostrarMantUsu();
                    this.dispose();
                } else {
                    numIntentos++;
                    if(numIntentos >= 3) {
                        JOptionPane.showMessageDialog(null, "Acceso Incorrecto. Verifique sus credenciales y estado.", "Error de Autenticación", JOptionPane.WARNING_MESSAGE);
                        System.exit(0);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtNroDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroDNIActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtNroDNI;
    // End of variables declaration//GEN-END:variables
}
