package Capa_Presentacion;

import Capa_Datos.clsConexion;
import Reportes.clsReportes;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author gabriel
 */
public class frmPruebasReportes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPruebasReportes.class.getName());

    /**
     * Creates new form frmPruebasReportes
     * @param parent
     * @param modal
     */
    public frmPruebasReportes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerReporte = new javax.swing.JButton();
        btnExportarPDF = new javax.swing.JButton();
        panelReporte = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTE");

        btnVerReporte.setText("Ver reporte");
        btnVerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReporteActionPerformed(evt);
            }
        });

        btnExportarPDF.setText("Exportar a PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        panelReporte.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnVerReporte)
                        .addGap(158, 158, 158)
                        .addComponent(btnExportarPDF))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(panelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerReporte)
                    .addComponent(btnExportarPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(panelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReporteActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingresa el nombre del jrxml");
        try {
            clsReportes.compilarReporte(nombre);
            JOptionPane.showMessageDialog(this, "todo salio bien");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnVerReporteActionPerformed

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
        exportarPDF();
    }//GEN-LAST:event_btnExportarPDFActionPerformed

    private void mostrarReporte() {
        try {

            clsReportes objR = new clsReportes();

            // Parámetros del reporte (si no tienes ninguno, usa un HashMap vacío)
            Map<String, Object> parametros = new HashMap<>();

            // Obtiene el visor interno
            JRViewer visor = objR.obtenerVisorInterno("ReporteUsuarios", parametros);

            // Limpia el panel y agrega el visor
            panelReporte.setLayout(new BorderLayout());
            panelReporte.removeAll();
            panelReporte.add(visor, BorderLayout.CENTER);
            panelReporte.revalidate();
            panelReporte.repaint();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void exportarPDF() {
        try {
            clsConexion objC = new clsConexion();
            objC.conectar();
            Connection con = objC.getCon();

            clsReportes objR = new clsReportes();

            Map<String, Object> parametros = new HashMap<>();

            // Abrir ventana para elegir dónde guardar el archivo
            javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
            selector.setDialogTitle("Guardar reporte como PDF");
            selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf"));

            // Sugerencia de nombre por defecto
            selector.setSelectedFile(new java.io.File("ReporteUsuarios.pdf"));

            int userSelection = selector.showSaveDialog(this);

            if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
                String ruta = selector.getSelectedFile().getAbsolutePath();

                // Asegurarse de que termine en .pdf
                if (!ruta.toLowerCase().endsWith(".pdf")) {
                    ruta += ".pdf";
                }

                objR.exportarAPDF("ReporteUsuarios", parametros, con, ruta);

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Reporte exportado correctamente:\n" + ruta);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al exportar el reporte: " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JButton btnVerReporte;
    private javax.swing.JPanel panelReporte;
    // End of variables declaration//GEN-END:variables
}
