package Capa_Presentacion;

import Reportes.clsReportes;
import java.awt.BorderLayout;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author gabriel
 */
public class frmRP_ServiciosTrabajadores extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmRP_ServiciosTrabajadores.class.getName());

    /**
     * Creates new form frmRP_ServiciosTrabajadores
     */
    public frmRP_ServiciosTrabajadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    String nombreUsu = frmMenuPrincipal.info_usu[0] + " " + frmMenuPrincipal.info_usu[1];

    private void mostrarReporte(Date fecha_inicio, Date fecha_final) throws Exception {
        try {
            clsReportes objR = new clsReportes();
            Map<String, Object> parametros = new HashMap<>();

            // 1. Mantenemos los parámetros Date para las consultas SQL
            parametros.put("fecha_inicio", fecha_inicio);
            parametros.put("fecha_fin", fecha_final);

            // 2. CREAMOS LOS NUEVOS PARÁMETROS STRING PARA LOS TEXTFIELD
            // Usamos el formato que querías
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            parametros.put("fecha_inicio_str", sdf.format(fecha_inicio));
            parametros.put("fecha_fin_str", sdf.format(fecha_final));

            // 3. Los parámetros de directorio y usuario
            parametros.put("REPORT_DIR", "src/Reportes/");
            parametros.put("SUBREPORT_DIR", "src/Reportes/");
            parametros.put("usuario", nombreUsu);

            // El resto de tu código sigue igual
            JRViewer visor = objR.obtenerVisorInterno("ServPorTrabajador", parametros);
            cont.setLayout(new BorderLayout());
            cont.removeAll();
            cont.add(visor, BorderLayout.CENTER);
            cont.revalidate();
            cont.repaint();

        } catch (Exception ex) {
            throw new Exception("Error al mostrar el reporte de servicios: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcFechaIni = new com.toedter.calendar.JDateChooser();
        jcFechaFin = new com.toedter.calendar.JDateChooser();
        cont = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Productividad de los trabajadores");

        btnMostrarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMostrarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/generar.png"))); // NOI18N
        btnMostrarReporte.setText("Generar reporte");
        btnMostrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReporteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fecha de inicio: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de fin: ");

        javax.swing.GroupLayout contLayout = new javax.swing.GroupLayout(cont);
        cont.setLayout(contLayout);
        contLayout.setHorizontalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contLayout.setVerticalGroup(
            contLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cont)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnMostrarReporte)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(1, 1, 1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jcFechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnMostrarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cont)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReporteActionPerformed
        try {
            if (jcFechaIni.getDate() == null || jcFechaFin.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Debes agregar una fecha inicial", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(jcFechaIni.getDate().after(jcFechaFin.getDate())) {
                JOptionPane.showMessageDialog(this, "La fecha inicial debe ser menor a la fecha final", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Date hoy = new Date(); // fecha actual
            if(jcFechaFin.getDate().after(hoy)) {
                JOptionPane.showMessageDialog(this, "La fecha final debe ser menor a la actual", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            Date fecha_inicio = jcFechaIni.getDate();
            Date fecha_final = jcFechaFin.getDate();
            mostrarReporte(fecha_inicio, fecha_final);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarReporte;
    private javax.swing.JDesktopPane cont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jcFechaFin;
    private com.toedter.calendar.JDateChooser jcFechaIni;
    // End of variables declaration//GEN-END:variables
}
