/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Capa_Presentacion;

import Capa_Datos.clsConexion; 
import Reportes.clsReportes;
import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author DIEGO SANDOVAL
 */

public class frmRP_ControlDemoras extends javax.swing.JDialog {

    /**
     * Creates new form frmRP_ControlDemoras
     */
    
    clsConexion objConexion = new clsConexion();
    
    public frmRP_ControlDemoras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.vistareporte.setVisible(false);
        
        cargarEstadosDesdeBD();
    }

    private void cargarEstadosDesdeBD() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("-- Seleccione --");
        
        try {
            String sql = "SELECT DISTINCT estado FROM ORDEN ORDER BY estado"; 
            ResultSet rs = objConexion.consultarBD(sql);
            
            while(rs.next()){
                modelo.addElement(rs.getString("estado"));
            }
            
            cboEstado.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar estados: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistareporte = new javax.swing.JPanel();
        cboEstado = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        vistareporte.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout vistareporteLayout = new javax.swing.GroupLayout(vistareporte);
        vistareporte.setLayout(vistareporteLayout);
        vistareporteLayout.setHorizontalGroup(
            vistareporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        vistareporteLayout.setVerticalGroup(
            vistareporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jButton3.setText("Generar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado de vehículos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vistareporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(vistareporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validar selección
            if (cboEstado.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un estado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Obtener el texto del combo
            String estadoSeleccionado = cboEstado.getSelectedItem().toString();

            // 3. Preparar contenedor
            Container contenedor = this.vistareporte;
            contenedor.removeAll();
            contenedor.setLayout(new BorderLayout());

            // 4. Parámetros
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("p_estado", estadoSeleccionado);
            parametros.put("REPORT_DIR", "src/Reportes/");

            // 5. Llamar al reporte
            // Asegúrate que el archivo .jasper se llame ReporteDemoras.jasper
            JRViewer objReporte = new clsReportes().reporteInterno("ReporteDemoras.jasper", parametros);

            if (objReporte != null) {
                contenedor.add(objReporte);
                contenedor.revalidate();
                contenedor.repaint();
                this.vistareporte.setVisible(true);
            } else {
                 JOptionPane.showMessageDialog(this, "No se encontraron registros para el estado: " + estadoSeleccionado);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error crítico: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel vistareporte;
    // End of variables declaration//GEN-END:variables
}
