package Capa_Presentacion;

import Capa_Logica.Repuesto;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Txiki Xavier Garaycochea Mendoza
 */
public class frmSeleccionarRepuestosOrden extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSeleccionarRepuestosOrden.class.getName());

    Repuesto objRepuesto = new Repuesto();
    int rep = 0;
    int cant = 0;
    double precio = 0;

    /**
     * Creates new form frmSeleccionarRepuestosOrden
     */
    public frmSeleccionarRepuestosOrden(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarRepuestos();
        txtPrecio.setEnabled(false);
    }

    public int getRep() {
        return rep;
    }

    public int getCant() {
        return cant;
    }

    public double getPrecio() {
        return precio;
    }
    
    private void pasarDatos(){
        cant = (int) spnStock.getValue();
        precio = Double.parseDouble(txtPrecio.getText());
        dispose();
    }

    private void listarRepuestos() {
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rsR = null;
        modelo.addColumn("Repuesto");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Estado");
        modelo.addColumn("Marca");
        modelo.addColumn("Descripción");
        try {
            rsR = objRepuesto.listarRepuestosListos();
            while (rsR.next()) {
                modelo.addRow(new Object[]{rsR.getString("nombre_repuesto"), rsR.getFloat("precio"), rsR.getInt("stock"),
                    rsR.getString("estado"), rsR.getString("nombre_marca"), rsR.getString("descripcion")});
            }
            tblRepuestos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al listar repuestos: " + e.getMessage());
        }
    }

    private void listarRepuestosFiltro(String filtro, String cont) {
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rsR = null;
        modelo.addColumn("Repuesto");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Estado");
        modelo.addColumn("Marca");
        modelo.addColumn("Descripción");
        try {
            if (filtro == "Nombre") {
                rsR = objRepuesto.buscarRepuesto_Nombre(cont);
                while (rsR.next()) {
                    modelo.addRow(new Object[]{rsR.getString("nombre_repuesto"), rsR.getFloat("precio"), rsR.getInt("stock"),
                        rsR.getString("estado"), rsR.getString("nombre_marca"), rsR.getString("descripcion")});
                }
                tblRepuestos.setModel(modelo);
            } else if (filtro == "Marca") {
                rsR = objRepuesto.buscarRepuesto_Marca(cont);
                while (rsR.next()) {
                    modelo.addRow(new Object[]{rsR.getString("nombre_repuesto"), rsR.getFloat("precio"), rsR.getInt("stock"),
                        rsR.getString("estado"), rsR.getString("nombre_marca"), rsR.getString("descripcion")});
                }
                tblRepuestos.setModel(modelo);
            } else {
                rsR = objRepuesto.listarRepuestosListos();
                while (rsR.next()) {
                    modelo.addRow(new Object[]{rsR.getString("nombre_repuesto"), rsR.getFloat("precio"), rsR.getInt("stock"),
                        rsR.getString("estado"), rsR.getString("nombre_marca"), rsR.getString("descripcion")});
                }
                tblRepuestos.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al listar repuestos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboFiltros = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepuestos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnStock = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELECIONAR REPUESTO DE SERVICIO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("FILTRAR REPUESTOS:");

        cboFiltros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Marca" }));
        cboFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltrosActionPerformed(evt);
            }
        });

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblRepuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRepuestosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRepuestos);

        btnAgregar.setText("AGREGAR REPUESTO");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Precio: ");

        jLabel3.setText("Stock: ");

        spnStock.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboFiltros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltrosActionPerformed

    }//GEN-LAST:event_cboFiltrosActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed

    }//GEN-LAST:event_txtFiltroKeyPressed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        String cont = txtFiltro.getText().trim();

        try {
            if (cont.trim().equals("")) {
                listarRepuestos();
            } else {
                listarRepuestosFiltro(cboFiltros.getSelectedItem().toString(), cont);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tblRepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRepuestosMouseClicked
        int fila = tblRepuestos.getSelectedRow();
        try {
            Double precio = Double.parseDouble(tblRepuestos.getValueAt(fila, 1).toString());
            txtPrecio.setText(precio.toString());
            ResultSet rsRep = objRepuesto.buscarRepuestoEstricto(tblRepuestos.getValueAt(fila, 0).toString());
            if(rsRep.next()){
                rep = rsRep.getInt("repuesto_id");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_tblRepuestosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int fila = tblRepuestos.getSelectedRow();
        if (fila != -1) {
            int cant = (int) spnStock.getValue();
            if (cant <= Integer.parseInt(tblRepuestos.getValueAt(fila, 2).toString())) {
                pasarDatos();
            } else {
                JOptionPane.showMessageDialog(rootPane, "La cantidad supera el stock");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un repuesto");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cboFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTable tblRepuestos;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
