/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Capa_Presentacion;

import Capa_Logica.Vehiculo;
import java.awt.HeadlessException;
import javax.swing.JComboBox;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.Timer;

/**
 *
 * @author CESAR
 */
public class frmVehiculo extends javax.swing.JInternalFrame {

    private Timer debounceTimer;
    int i = 0;

    public frmVehiculo() {
        initComponents();
        listarMarca();
        ResultSet rs = new Vehiculo().listarVehiculo();
        listarVehiculo(rs);
        lblNumCars.setText(String.valueOf(i));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblClient = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboMarca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtDni = new javax.swing.JTextField();
        btnBuscarUser = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtGeneral = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboFilterBrand = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNumCars = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnListarTodos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBajaAlta = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento de vehiculos");
        setAutoscrolls(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/client.png"))); // NOI18N
        jLabel4.setText("Cliente:");

        lblClient.setText("_____________________________________________________");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Modelo:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Número placa:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Color:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Marca:");

        cboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMarcaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Número de documento:");

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Descripción:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        btnBuscarUser.setText("Buscar");
        btnBuscarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(txtModel)
                            .addComponent(cboMarca, 0, 151, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txtColor))
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(lblClient, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addComponent(lblClient)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneralActionPerformed(evt);
            }
        });
        txtGeneral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGeneralKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Marca");

        cboFilterBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        cboFilterBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFilterBrandActionPerformed(evt);
            }
        });

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCarsMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblCars);

        jPanel2.setBackground(new java.awt.Color(255, 61, 61));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lista de vehiculos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Total de vehiculos:");

        lblNumCars.setText("__________");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Busqueda General");

        btnListarTodos.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnListarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/listar.png"))); // NOI18N
        btnListarTodos.setText("Listar Todos");
        btnListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(66, 66, 66)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(cboFilterBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblNumCars)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnListarTodos))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFilterBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarTodos)
                    .addComponent(jLabel11)
                    .addComponent(lblNumCars))
                .addGap(27, 27, 27))
        );

        jPanel5.setBackground(new java.awt.Color(255, 61, 61));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mantenimiento de Vehículos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nuevoVehiculo.png"))); // NOI18N
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnUpdate.setText("Modificar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBajaAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/darBaja.png"))); // NOI18N
        btnBajaAlta.setText("Dar baja/alta");
        btnBajaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAltaActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(102, 102, 102));
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBajaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBajaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarVehiculo(ResultSet rs) {
        DefaultTableModel tm = new DefaultTableModel();

        String[] columns = {"vehiculo_id", "modelo", "color", "num_placa", "estado", "fecha_registro", "marca", "num_documento", "cliente"};
        for (int i = 0; i < columns.length; i++) {
            tm.addColumn(columns[i]);
        }

        try {
            while (rs.next()) {
                i++;
                Object[] row = new Object[columns.length];
                for (int j = 0; j < columns.length; j++) {
                    row[j] = rs.getString(columns[j]);
                    if (columns[j].equalsIgnoreCase("estado")) {
                        row[j] = rs.getString(columns[j]).equalsIgnoreCase("t") ? "Activo" : "Inactivo";
                    }
                }
                tm.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        tblCars.setModel(tm);
    }

    private void listarMarca() {
        JComboBox<String> myCbo = new JComboBox<>();
        JComboBox<String> myCbo2 = new JComboBox<>();
        ResultSet rs = new Vehiculo().listarMarcas();

        myCbo2.addItem("Todos");

        try {
            while (rs.next()) {
                myCbo.addItem(rs.getString("nombre_marca"));
                myCbo2.addItem(rs.getString("nombre_marca"));
            }
        } catch (SQLException ex) {
            System.getLogger(ex.getMessage());
        }
        cboMarca.setModel(myCbo.getModel());
        cboFilterBrand.setModel(myCbo2.getModel());
    }

    private void limpiar() {
        txtDni.setText("");
        txtModel.setText("");
        txtPlaca.setText("");
        cboMarca.setSelectedIndex(0);
        txtColor.setText("");
        txtDesc.setText("");
    }

    private void btnBajaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAltaActionPerformed
        Vehiculo vh = new Vehiculo();
        int filaSelec = tblCars.getSelectedRow();
        if (filaSelec != -1) {
            int vehiculo_id = Integer.parseInt(tblCars.getValueAt(filaSelec, 0).toString());
            try {
                int opcion = JOptionPane.showConfirmDialog(
                        this,
                        "Estas seguro de modificar este vehiculo?", "Confirmar dar baja/alta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (opcion == JOptionPane.YES_OPTION) {
                    int rs = vh.darBajaAlta(vehiculo_id);
                    if (rs == 1) {
                        JOptionPane.showMessageDialog(this, "Se dio de baja/alta el vehiculo seleccionado");
                        ResultSet rs1 = new Vehiculo().listarVehiculo();
                        listarVehiculo(rs1);
                        limpiar();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            } finally {

            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe elegir un vehiculo para dar de baja/alta");
        }
    }//GEN-LAST:event_btnBajaAltaActionPerformed

    private void cboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMarcaActionPerformed

    }//GEN-LAST:event_cboMarcaActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed

    }//GEN-LAST:event_txtDniActionPerformed

    private void btnBuscarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUserActionPerformed
        String dni = txtDni.getText();
        ResultSet rs = new Vehiculo().buscarCliente(dni);
        try {
            if (rs != null && rs.next()) {
                lblClient.setText(rs.getString("apellidos") + " " + rs.getString("nombres"));
            } else {
                lblClient.setText("Cliente no encontrado");
            }
        } catch (SQLException ex) {
            System.getLogger(ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarUserActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Vehiculo vh = new Vehiculo();

        try {
            String dni = txtDni.getText().trim();

            if (!dni.matches("^[0-9]{8}$")) {
                JOptionPane.showMessageDialog(null, "El DNI debe tener 8 dígitos.");
                return;
            }

            ResultSet rs1 = vh.buscarCliente(dni);
            if (!rs1.next()) {
                JOptionPane.showMessageDialog(null, "No existe un cliente con ese DNI.");
                return;
            }
            int cliente_id = rs1.getInt("cliente_id");

            String nombreMarca = cboMarca.getSelectedItem().toString().trim();
            ResultSet rs2 = vh.buscarIdMarca(nombreMarca);

            if (!rs2.next()) {
                JOptionPane.showMessageDialog(null, "La marca seleccionada no existe.");
                return;
            }
            int marca_id = rs2.getInt("marca_id");

            String modelo = txtModel.getText().trim();
            if (modelo.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El modelo no puede estar vacío.");
                return;
            }

            String color = txtColor.getText().trim();
            if (color.length() > 30) {
                JOptionPane.showMessageDialog(null, "El color no debe exceder 30 caracteres.");
                return;
            }

            String placa = txtPlaca.getText().trim();

            if (!placa.matches("^[0-9A-Z]{6,8}$")) {
                JOptionPane.showMessageDialog(null,
                        "La placa debe tener entre 6 y 8 caracteres en mayúsculas (0-9, A-Z).");
                return;
            }

            // Verificar unicidad de placa
            if (vh.placaExiste(placa)) {
                JOptionPane.showMessageDialog(null, "La placa ingresada ya existe.");
                return;
            }

            String descripcion = txtDesc.getText().trim();

            vh.insertarVehiculo(modelo, placa, descripcion, color, cliente_id, marca_id);

            ResultSet rs3 = vh.listarVehiculo();
            listarVehiculo(rs3);
            limpiar();

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cboFilterBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFilterBrandActionPerformed

        ResultSet rs = new Vehiculo().listarPorFiltros(txtGeneral.getText(), cboFilterBrand.getSelectedItem().toString());

        listarVehiculo(rs);

    }//GEN-LAST:event_cboFilterBrandActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int filaSelec = tblCars.getSelectedRow();
        Vehiculo vh = new Vehiculo();

        if (filaSelec != -1) {

            int vehiculo_id = Integer.parseInt(tblCars.getValueAt(filaSelec, 0).toString());

            try {

                int opcion = JOptionPane.showConfirmDialog(
                        this,
                        "¿Estás seguro de modificar este vehículo?",
                        "Confirmar Modificación",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (opcion != JOptionPane.YES_OPTION) {
                    return;
                }

                String dni = txtDni.getText().trim();

                if (!dni.matches("^[0-9]{8}$")) {
                    JOptionPane.showMessageDialog(this, "El DNI debe tener 8 dígitos.");
                    return;
                }

                ResultSet rs1 = vh.buscarCliente(dni);
                if (!rs1.next()) {
                    JOptionPane.showMessageDialog(this, "No existe un cliente con ese DNI.");
                    return;
                }
                int cliente_id = rs1.getInt("cliente_id");

                String nombreMarca = cboMarca.getSelectedItem().toString().trim();
                ResultSet rs2 = vh.buscarIdMarca(nombreMarca);

                if (!rs2.next()) {
                    JOptionPane.showMessageDialog(this, "La marca seleccionada no existe.");
                    return;
                }
                int marca_id = rs2.getInt("marca_id");

                String modelo = txtModel.getText().trim();
                if (modelo.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "El modelo no puede estar vacío.");
                    return;
                }

                String color = txtColor.getText().trim();
                if (color.length() > 30) {
                    JOptionPane.showMessageDialog(this, "El color no debe exceder 30 caracteres.");
                    return;
                }

                String placa = txtPlaca.getText().trim();

                if (!placa.matches("^[0-9A-Z]{6,8}$")) {
                    JOptionPane.showMessageDialog(this,
                            "La placa debe tener entre 6 y 8 caracteres en mayúsculas (0-9, A-Z).");
                    return;
                }

                if (vh.placaExisteParaOtroVehiculo(placa, vehiculo_id)) {
                    JOptionPane.showMessageDialog(this, "La placa ingresada ya está asociada a otro vehículo.");
                    return;
                }

                String descripcion = txtDesc.getText().trim();

                int rpta = vh.actualizarVehiculo(
                        vehiculo_id,
                        modelo,
                        placa,
                        descripcion,
                        color,
                        cliente_id,
                        marca_id
                );

                if (rpta == 1) {
                    ResultSet rs = new Vehiculo().listarVehiculo();
                    listarVehiculo(rs);
                    limpiar();
                    JOptionPane.showMessageDialog(this, "Vehículo modificado correctamente.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe elegir un vehículo para modificar.");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneralActionPerformed

    }//GEN-LAST:event_txtGeneralActionPerformed

    private void txtGeneralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneralKeyPressed
        if (debounceTimer != null && debounceTimer.isRunning()) {
            debounceTimer.stop();
        }

        debounceTimer = new Timer(300, (e) -> {
            String filter = txtGeneral.getText();
            String marca = cboFilterBrand.getSelectedItem().toString();

            ResultSet rs = new Vehiculo().listarPorFiltros(filter, marca);
            listarVehiculo(rs);
        });

        debounceTimer.setRepeats(false);
        debounceTimer.start();
    }//GEN-LAST:event_txtGeneralKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int filaSelec = tblCars.getSelectedRow();
        if (filaSelec != -1) {
            int vehiculo_id = Integer.parseInt(tblCars.getValueAt(filaSelec, 0).toString());
            try {
                int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este vehiculo?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (opcion == JOptionPane.YES_OPTION) {
                    int rpta = new Vehiculo().eliminar(vehiculo_id);
                    if (rpta == 1) {
                        JOptionPane.showMessageDialog(this, "Se elimino el vehiculo seleccionado");
                        ResultSet rs = new Vehiculo().listarVehiculo();
                        listarVehiculo(rs);
                        limpiar();
                    }
                }

            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            } finally {

            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe elegir un vehiculo para eliminar");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void tblCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarsMouseClicked

    }//GEN-LAST:event_tblCarsMouseClicked

    private void tblCarsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarsMousePressed
        Vehiculo vh = new Vehiculo();
        try {
            int idx = tblCars.getSelectedRow();
            int id = Integer.parseInt(tblCars.getValueAt(idx, 0).toString().trim());
            ResultSet rs = vh.buscarPorId(id);
            rs.next();
            txtModel.setText(rs.getString("modelo"));
            txtPlaca.setText(rs.getString("num_placa"));
            txtColor.setText(rs.getString("color"));
            txtDesc.setText(rs.getString("descripcion"));
            txtDni.setText(rs.getString("num_documento"));
            int cboIdx = vh.buscarRankMarca(tblCars.getValueAt(idx, 6).toString().trim());
            cboMarca.setSelectedIndex(cboIdx - 1);

        } catch (Exception ex) {
            Logger.getLogger(frmVehiculo.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }
    }//GEN-LAST:event_tblCarsMousePressed

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
        ResultSet rs = new Vehiculo().listarVehiculo();
        listarVehiculo(rs);
    }//GEN-LAST:event_btnListarTodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaAlta;
    private javax.swing.JButton btnBuscarUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboFilterBrand;
    private javax.swing.JComboBox<String> cboMarca;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblNumCars;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtGeneral;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
